insert into task_list(task_name, task_description, task_priority, task_status, task_archived) values ('Futbol', 'Jugar al futbol', 'HIGH', 'ACTIVE', 0)
insert into task_list(task_name, task_description, task_priority, task_status, task_archived) values ('Compras', 'Hacer las compras', 'HIGH', 'ACTIVE', 0)
insert into task_list(task_name, task_description, task_priority, task_status, task_archived) values ('Farmacia', 'Ir a la Farmacia', 'MEDIUM', 'ACTIVE', 0)
insert into task_list(task_name, task_description, task_priority, task_status, task_archived) values ('Juan', 'Saludar a Juan', 'LOW', 'COMPLETED', 0)
insert into task_list(task_name, task_description, task_priority, task_status, task_archived) values ('Albañil', 'Llamar al albañil', 'HIGH', 'ACTIVE', 0)